---
title: "Variants distribution along the cohort"
date: "2026-07-17"
output:
    github_document
always_allow_html: true
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}

knitr::opts_chunk$set(message = F, warning = F)

library(kableExtra)
library(tidyverse)
library(ggtext)
library(ggh4x)
library(here)
library(knitr)

set_theme(theme_classic(base_size = 16) +
              theme(axis.text = element_text(size = 12)))

```

```{r}

genes_per_amplicon <- c(
    "NC_002677.1:2275293-2275762" = "rpoB",
    "NC_002677.1:7338-7913" = "gyrA",
    "NC_002677.1:6572-7092" = "gyrB",
    "NC_002677.1:296740-297537" = "folP1",
    "NC_002677.1:1228849-1229606" = "folP2",
    "NC_002677.1:1343877-1344282" = "23S rRNA I",
    "NC_002677.1:1345386-1345951" = "23S rRNA II"
)

vardf <- read.delim(here("data/raw_data/variants/Stats/var_stats.txt"),
                    check.names = F)

varstats <- vardf %>%
    separate_wider_delim(
        cols = DP4,
        delim = ",",
        names = c("ref_fwd", "ref_rev", "alt_fwd", "alt_rev")
    ) %>%
    mutate(
        SAMPLE = factor(
            SAMPLE,
            levels = unique(vardf$SAMPLE),
            labels = paste("Sample", 1:8)
        ),
        GENE = genes_per_amplicon[AMPLICON],
        across(c(alt_fwd, alt_rev, ref_fwd, ref_rev), as.numeric)
    ) %>%
    rowwise() %>%
    mutate(p_val = fisher.test(matrix(
        c(ref_fwd, ref_rev, alt_fwd, alt_rev),
        nrow = 2,
        byrow = T
    ))$p.value,
    FS = -log10(p_val)) %>%
    ungroup() %>%
    mutate(AF = (alt_fwd + alt_rev) / (ref_fwd + ref_rev + alt_fwd + alt_rev)) %>%
    select(SAMPLE, GENE, POS, REF, ALT, QUAL, DP, AF, FS, Is_Ti, Is_Ts)

write.csv(varstats,
          here("data/processed_data/variants_stats.csv"),
          row.names = F)

glimpse(varstats)

```

```{r}

dp_max <- 30
qual_max <- 100

varstats %>% group_by(GENE) %>%
    mutate(AF = AF * 100) %>% 
    summarise(
        n = n(),
        n_dp_200 = sum(DP > dp_max),
        n_qual_100 = sum(QUAL > qual_max),
        n_filtro = sum(DP > dp_max & QUAL > qual_max),
        af_min_total = min(AF, na.rm = TRUE),
        af_max_total = max(AF, na.rm = TRUE),
        af_min_dp = min(AF[DP > dp_max], na.rm = TRUE),
        af_max_dp = max(AF[DP > dp_max], na.rm = TRUE),
        af_min_qual = min(AF[QUAL > qual_max], na.rm = TRUE),
        af_max_qual = max(AF[QUAL > qual_max], na.rm = TRUE),
        af_min_filtro = min(AF[DP > dp_max &
                                   QUAL > qual_max], na.rm = TRUE),
        af_max_filtro = max(AF[DP > dp_max &
                                   QUAL > qual_max], na.rm = TRUE)
    ) %>%
    complete(
        GENE = c(
            "rpoB",
            "gyrA",
            "gyrB",
            "folP1",
            "folP2",
            "23S rRNA I",
            "23S rRNA II"
        ),
        fill = list(
            n = 0,
            n_dp_200 = 0,
            n_qual_100 = 0,
            n_filtro = 0,
            af_min_total = 0,
            af_max_total = 0,
            af_min_dp = 0,
            af_max_dp = 0,
            af_min_qual = 0,
            af_max_qual = 0,
            af_min_filtro = 0,
            af_max_filtro = 0
        )
    ) %>%
    mutate(
        prop_retencao = ifelse(n == 0, 0, sprintf("%.1f%%", (n_filtro / n * 100))),
        af_total_label = case_when(
            n == 0 ~ "-",
            n == 1 ~ sprintf("%.1f%%", af_min_total),
            TRUE ~ sprintf("%.1f%% - %.1f%%", af_min_total, af_max_total)
        ),
        af_dp_label = case_when(
            n_dp_200 == 0 ~ "-",
            n_dp_200 == 1 ~ sprintf("%.1f%%", af_min_dp),
            TRUE ~ sprintf("%.1f%% - %.1f%%", af_min_dp, af_max_dp)
        ),
        af_qual_label = case_when(
            n_qual_100 == 0 ~ "-",
            n_qual_100 == 1 ~ sprintf("%.1f%%", af_min_qual),
            TRUE ~ sprintf("%.1f%% - %.1f%%", af_min_qual, af_max_qual)
        ),
        af_filtro_label = case_when(
            n_filtro == 0 ~ "-",
            n_filtro == 1 ~ sprintf("%.1f%%", af_min_filtro),
            TRUE ~ sprintf("%.1f%% - %.1f%%", af_min_filtro, af_max_filtro)
        )
    ) %>%
    select(
        GENE,
        n,
        af_total_label,
        n_dp_200,
        af_dp_label,
        n_qual_100,
        af_qual_label,
        n_filtro,
        af_filtro_label,
        prop_retencao
    ) %>% 
    kable(align = "lccccccccl",
          col.names = c("Genes", "Counts", "Allelic Frequency", "Counts", "Allelic Frequency", "Counts", "Allelic Frequency", "Counts", "Allelic Frequency", "Prop. of retention")) %>% 
    kable_classic() %>% 
    column_spec(1, italic = T) %>% 
    add_header_above(c(
        " " = 1,
        "Total" = 2,
        "DP > 30" = 2,
        "QUAL > 100" = 2,
        "DP > 30 & QUAL > 100" = 2,
        " " = 1
    ))
```

```{r}

cor_dp_qual <- cor.test(log10(varstats$DP), varstats$QUAL)
r <- unname(cor_dp_qual$estimate)
p <- cor_dp_qual$p.value

cor_label <- sprintf("r = %.1f; p = %.1e", r, p)

varstats %>%
    ggplot(aes(y = QUAL, x = DP)) +
    labs(y = "Calling quality", x = bquote("Read depth" ~ (log[10] ~ "scale"))) +
    geom_point(shape = 21, fill = "gray", alpha = 0.7) +
    geom_smooth(method = "lm") +
    annotate(
        "text",
        label = cor_label,
        x = 5,
        y = 225,
        size = 6,
        hjust = 0
    ) +
    scale_y_continuous(expand = expansion(mult = c(0.05, 0.05))) +
    scale_x_continuous(
        trans = "log10",
        label = scales::label_log(),
        expand = expansion(mult = c(0.02, 0.02))
    )
```